### ISSUE TITLE
spack droped "fail to load cuda@11.7"

### ISSUE THREAD

**Issue by wuliJerry** [gty111/SimpleUseGpgpuSim#1]
Hi, I was following your wizard until the step that runs `bash run.sh`.  Instead of initializing the project, it showed:
```
==> Error: Spec 'cuda@11.7' matches no installed packages.
fail to load cuda@11.7
```
Should I also install the respective version of cuda as a dependency package in the step `spack install gpgpu-sim%gcc@7.5.0 ^ mesa~llvm` by using `spack install gpgpu-sim%gcc@7.5.0 ^ mesa~llvm ^ cuda@11.7`?

**Comment by gty111** [comment]
It seems that your spack didn't install cuda 11.7 .  So you need to install cuda using spack via `spack install cuda@11.7` and specify the version of cuda in the script `run.sh`. Or you have installed one version of cuda , you can directly specify the version of cuda you have installed in the script `run.sh`.
